### ISSUE TITLE
Datenschutz / Nutzungsbedingungen usw.

### ISSUE THREAD

**Issue by aendu92** [SmashGrade/documentation#2]
Verweis auf folgende hftm Seiten: 
https://www.hftm.ch/de/datenschutz
https://www.hftm.ch/de/allgemeine-geschaeftsbedingungen-hftm

Eigene Inputs noch ergänzen 

-> eigenes Dokuemnt

**Comment by BryanBrotschi** [comment]
gemäss rücksprache mit michael kein separates dokument nötig. der verweis auf die beiden seiten der hftm wurde in der dokumentation als kapitel ergänzt.
